/**
 * @description       : 
 * @author            : robert
 * @group             : dcit-hf
 * @last modified on  : 07-14-2021
 * @last modified by  : robert
 * Modifications Log 
 * Ver   Date         Author   Modification
 * 1.0   07-09-2021   robert   Initial Version
**/
// global class AccountSiteBatch implements Database.Batachable<sObject>, Database.Statedul, Schedulable{
//     global void execute(SchedulableContext sc){
//         AccountSite();
//     }
// }

// System.schedule('AccountSiteBatchSchedule', '0 0 0 * * ?', new AccountSiteBatch());